### ISSUE TITLE
The DeFi industry moves towards zk proofs despite its problems

### ISSUE THREAD

**Issue by GavT** [obscuronet/obscuro-project#9]
Obscuro uses SGX because this is the better solution compared to zero knowledge proofs however the level of interest and optimism about zk proofs could lead the DeFi industry to head towards zk proofs even though this is the sub-optimal solution.

Mitigation: investigate the state of zk proofs and have a robust narrative prepared on why Obscuro's design is superior

**Comment by moraygrieve** [comment]
@GavT is this still relevant?

**Comment by GavT** [comment]
We have a robust answer to questions around zkps so closing this.
